### PR TITLE
Add Jammy and CentOS Stream 9

### PR DESCRIPTION
**Pull request by mamercad**
Added `build_one.sh` helper script as well for building a single target.

They built for me locally:

```shell
❯ docker images | grep packagingbuild | grep -E 'stream|jammy' | awk '{print $1" "$2}'
stackstorm/packagingbuild centosstream9
stackstorm/packagingbuild jammy
```

### CODE REVIEW

**Comment by armab** [comment]
Thanks for the first steps!

I've added `jammy` and `centosstream9` to the Docker Hub CI settings, so hopefully we'll see the builds on a new commits in this PR.

**Comment by mamercad** [comment]
> Thanks for the first steps!
> 
> I've added `jammy` and `centosstream9` to the Docker Hub CI settings, so hopefully we'll see the builds on a new commits in this PR.

No problem - feels like we may need to add/update Docker CI things?

**Comment by mamercad** [comment]
> > Thanks for the first steps!
> > I've added `jammy` and `centosstream9` to the Docker Hub CI settings, so hopefully we'll see the builds on a new commits in this PR.
> 
> No problem - feels like we may need to add/update Docker CI things?

Ah, we should do #110; I'll probably take a crack at it `$soon`.

**Comment by armab** [comment]
> feels like we may need to add/update Docker CI things?

Yeah, just updated it. You may still need to push new commits for the new tags to build.

Closed #110 as Docker Hub builds are working again.

**Comment by mamercad** [comment]
> Closed #110 as Docker Hub builds are working again as I see them in GH status checks.
> 
> > feels like we may need to add/update Docker CI things?
> 
> Yeah, just updated it. You may still need to push new commits for the new tags to build for this PR.

Cool, I see `centosstream9` and `jammy` passing now.

**Comment by mamercad** [comment]
> > Closed #110 as Docker Hub builds are working again as I see them in GH status checks.
> > > feels like we may need to add/update Docker CI things?
> > 
> > 
> > Yeah, just updated it. You may still need to push new commits for the new tags to build for this PR.
> 
> Cool, I see `centosstream9` and `jammy` passing now.

As usual, I'm participating in [Hacktoberfest](https://hacktoberfest.com/), do you mind adding the `hacktoberfest-accepted` label to this pull request please?

**Review by armab — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
