### PR TITLE
Update to use PY3 on EL7

### PR DESCRIPTION
**Pull request by amanda11**
Update the EL7 docker containers to install python3, and pip3 and python3-virtualenv for building ST2 RPM.

Part of https://github.com/StackStorm/discussions/issues/54

### CODE REVIEW

**Comment by amanda11** [comment]
Notes. I updated the buildpack file, but have not tested it. How do I test it? The comments state that it is for building enterprise RPMs? Is it still used?

**Comment by armab** [comment]
According to https://github.com/search?q=org%3AStackStorm+buildpack&type=code, `buildpack` Docker images are still used in https://github.com/StackStorm/st2-auth-ldap, https://github.com/StackStorm/st2-auth-backend-sso-saml2 and https://github.com/StackStorm/st2-rbac-backend repositories.

**Review by armab — APPROVED** [review]
Looks good! :+1: 

After merging the new images should be deployed to Docker Hub to verify the https://github.com/StackStorm/st2-packages/pull/671 PR as a next step.

**Comment by amanda11** [comment]
Just going to verify building one of the enterprise components before this is merged. Currently investigating some issues.

**Comment by amanda11** [comment]
Putting to draft whilst try to resolve buildpack issues. The main packagingbuild and packagingtest are good to go, so could take out the buildpack changes instead. But will need to resolve to be able to get the RBAC/LDAP pages built for EL7 PY3.

**Comment by armab** [comment]
@amanda11 I suggest to ship the working `packagingbuild` Docker images first in this PR so we can merge it and worry about the rbac/ldap and `buildpack` later.

**Comment by amanda11** [comment]
@armab @blag OK to merge this? Until the st2-packages are in, then it will break the buliding of packages for EL7. 

But want to get in, so that can test the EL7/Py3 ST2 PR for st2-packages change is good to go (this will make ST2 package for EL7 use python3).

**Comment by amanda11** [comment]
Spoke wiht @blag on slack, going to merge, and then re-set off the st2-packages PR build.

**Pull request merged**
