### PR TITLE
Adding libldap2-dev libsasl2-dev dependencies for Ubuntu xenial and bionic

### PR DESCRIPTION
**Pull request by hnanchahal**
Part of https://github.com/StackStorm/st2-packages/pull/674 and https://github.com/StackStorm/st2/pull/5082

Building LDAP requires `libldap2-dev` and `libsasl2-dev` as a build dependencies.

### CODE REVIEW

**Review by armab — APPROVED** [review]
That should do it :+1: 

Just waiting for more CI checks to be reported from the Docker Hub before merging it.

**Comment by armab** [comment]
The build error we got for these new changes is the following:
```
04 Not Found [IP: 91.189.88.142 80]
Get:92 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 python3-magic all 1:5.25-2ubuntu1.4 [5440 B]
Err:91 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libldap2-dev amd64 2.4.42+dfsg-2ubuntu3.10
404 Not Found [IP: 91.189.88.142 80]
Fetched 10.0 MB in 2s (4552 kB/s)
[91mE[0m
[91m: [0m
[91mFailed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.42+dfsg-2ubuntu3.10_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
[0m
[91m
[0m
[91mE[0m
[91m: [0m
[91mFailed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openldap/libldap2-dev_2.4.42+dfsg-2ubuntu3.10_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
```

There is probably a need of another `apt-get update` command.

**Comment by hnanchahal** [comment]
> The build error we got for these new changes is something along the lines:
> 
> ```
> 04 Not Found [IP: 91.189.88.142 80]
> Get:92 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 python3-magic all 1:5.25-2ubuntu1.4 [5440 B]
> Err:91 http://security.ubuntu.com/ubuntu xenial-security/main amd64 libldap2-dev amd64 2.4.42+dfsg-2ubuntu3.10
> 404 Not Found [IP: 91.189.88.142 80]
> Fetched 10.0 MB in 2s (4552 kB/s)
> �[91mE�[0m
> �[91m: �[0m
> �[91mFailed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openldap/libldap-2.4-2_2.4.42+dfsg-2ubuntu3.10_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
> �[0m
> �[91m
> �[0m
> �[91mE�[0m
> �[91m: �[0m
> �[91mFailed to fetch http://security.ubuntu.com/ubuntu/pool/main/o/openldap/libldap2-dev_2.4.42+dfsg-2ubuntu3.10_amd64.deb 404 Not Found [IP: 91.189.88.142 80]
> ```
> 
> There is probably a need of another `apt-get update` command.

Updated

**Comment by armab** [comment]
Merging as `/packagingbuild/bionic` and `/packagingbuild/xenial` Docker builds passed.
It'll take some time for images to get deployed to Docker Hub after merging.

**Pull request merged**
