### PR TITLE
Tidy up - remove xenial

### PR DESCRIPTION
**Pull request by amanda11**

### CODE REVIEW

**Comment by armab** [comment]
I've disabled the CI build for xenial in Docker Hub and triggered new build.
Let's see if all tests are green now.

**Review by armab — APPROVED** [review]
:+1: 
considering CI is happy

**Comment by amanda11** [comment]
@armab Not sure what happens on the tests, as it now only shows 1 check, when showed 4 before.. It's a bit odd how it reports the CI tests on this repo...
Are you able to check if they are ok - I just get to a 404 page...

**Comment by armab** [comment]
Docker Hub is weird.
We expect 8 successful CI checks there. 4 OS flavors x 2 Docker images (packagingtest + packagingbuild)

**Comment by armab** [comment]
Looks all the CI checks passed! :heavy_check_mark:

**Pull request merged**
